version: '3'

services:
  app:
    build: .
    env_file:
      - .env 
    environment: 
      - DATABASE_URI=postgresql://postgres:admin@postgres:5432/postgres
    command: ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh
    image: stephan-token
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres

  webhook_manager:
    image: stephan-token
    env_file:
      - .env 
    environment: 
      - DATABASE_URI=postgresql://postgres:admin@postgres:5432/postgres
    command: python reset_webhooks.py
    depends_on:
      - app

  postgres:
    image: postgres:12
    restart: unless-stopped
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes: 
      - pg_data:/var/lib/postgresql/data:cached

volumes: 
  pg_data:

