"""Add Nonce

Revision ID: 7df42f2dd6aa
Revises: 9c9483a46a60
Create Date: 2021-05-12 22:13:46.584844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df42f2dd6aa'
down_revision = '9c9483a46a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonce',
    sa.Column('nonce', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonce')
    # ### end Alembic commands ###
