"""Move nonce to account

Revision ID: c56538125a9e
Revises: 7df42f2dd6aa
Create Date: 2021-05-20 22:08:21.897308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56538125a9e'
down_revision = '7df42f2dd6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonce')
    op.add_column('account', sa.Column('nonce', sa.INTEGER(), nullable=True))

    op.execute('UPDATE account SET nonce = 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'nonce')
    op.create_table('nonce',
    sa.Column('nonce', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('nonce', name='nonce_pkey')
    )
    # ### end Alembic commands ###
